---
helpers:
  Mus4:    MuseScore4
  MusEdit:   ${Mus4} ${File}
  Abc2XmlPy: ./context/abc2xml.py
  MusStyle1: ./context/svg.mss
  TmpDir:    ./tmp
  Audacity:  "audacity ${Mp3File}"
  Mscz2Xml:  "${Mus4} ${File} -f -o ${XmlFile}"
  Xml2Mscz:  "${Mus4} ${XmlFile} -f -o ${MsczFile}"
  Mscz2Img:  "${Mus4} ${File} -T 5 -S ${MusStyle1} -o ${ImgFile}"
  Abc2Xml:   "${Python} ${Abc2XmlPy} -b -o ${XmlDir} ${AbcFile}"
  Abc2Img:   "${Abc2Ps} ${AbcFile} -g -O ${ImgFile}"
  Python:    python3
  MidiPort:  Synth

